# Generated by Django 2.2 on 2022-03-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='tube.Tag'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='tube.Video'),
        ),
    ]
